name: ci

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2
      - name: Run editorconfig-checker
        run: editorconfig-checker

  build:
    needs: editorconfig
    runs-on: ubuntu-24.04
    container: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v4
      - name: Build sysmodule
        run: ./build.sh
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: systime
          path: out/*
